Update cosmos sample from track1 to track2(Developing a Java app usin…
Azure-Samples/azure-cosmos-db-sql-api-async-java-getting-started pull request #7
Opened 2020-05-27 10:08 UTC by Melanie-Ma

Update cosmos sample from track1 to track2(Developing a Java app using Azure Cosmos DB Async Java SDK)

2020-11-25 20:49 UTC, jongio requested changes

2020-11-25 20:49 UTC, jongio commented on azure-cosmosdb-get-started/pom.xml
> +      <version>4.0.0-preview.1</version>
Please use the latest GA version.

2020-12-01 16:47 UTC, jongio commented
@kushagraThapar - Can you please review?

2020-12-01 17:27 UTC, kushagraThapar commented
@jongio - I have the same opinion on this getting started guide as I did for the samples. We already have azure-cosmos-java-getting-started guide based on track 2 library cosmos V4 SDK here - https://github.com/Azure-Samples/azure-cosmos-java-getting-started

I think we should just redirect this to the existing one. Thoughts ?

2020-12-10 22:15 UTC, jongio commented
@Melanie-Ma - Can you please update this one to point to the new one?

@tzhanl

2020-12-11 09:10 UTC, Melanie-Ma commented
@jongio please review.

2020-12-11 18:37 UTC, jongio approved these changes

2020-12-11 19:28 UTC, kushagraThapar approved these changes
LGTM

2020-12-11 23:11 UTC, merged